### ISSUE TITLE
error

### ISSUE THREAD

**Issue by wi6ck** [bifravst/random-words#34]
okay so im tryna use the code to make my discord bot (coded w/ discord.js) send randomly generated words in a sentence

(eg: hi test word sky blue tree fall computer)

this is my line of code which uses the random words generator;

.addFields({ name: "Code:", value: randomWords()})

and this is the error:

error [InteractionAlreadyReplied]: The reply to this interaction has already been sent or deferred.
    at ChatInputCommandInteraction.reply (C:\Users\no\Downloads\Slash_Command_Package_v14\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:102:46)
    at Object.execute (C:\Users\no\Downloads\Slash_Command_Package_v14\src\events\interactionCreate.js:18:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Emitted 'error' event on Client instance at:
    at emitUnhandledRejectionOrErr (node:events:394:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21) {
  code: 'InteractionAlreadyReplied'

**Comment by coderbyheart** [comment]
There is a problem in the way you interact with the discord API. This is not is problem caused by this library.
